Fix NoSuchMethodError Exceptions on < 1.7.9  R0.3  Builds of Bukkit Since Bukkit 1,7,9 R0.3, the return type of the "Bukkit.getOnlinePlayers()" has changed, which breaks these plugin when using the newer API on older versions. This can be bypassed using reflection